import wedding0ne from "./image/weddingbanner2.avif"
import WeddingTwo from "./image/weddingbanner3.jpg"
import logwedding from "./image/Group 1 (9).png"
import facebook from "./image/facebook.svg"
import twitter from "./image/twitter.svg"
import linkedin from "./image/linkedin.svg"
import erroeImg from "./image/error.avif"
import homeimg1 from  "./allImages/home/1.webp"
import homeimg2 from  "./allImages/home/2.webp"
import homeimg3 from  "./allImages/home/4.webp"
import homeimg52 from  "./allImages/home/52.webp"
import homeimg21 from  "./allImages/home/imgHome21.webp"
import homeimg22 from  "./allImages/home/line.webp"
import imgHome3 from  "./allImages/home/imgHome3.webp"
import imghome23 from  "./allImages/home/imgHome22.webp"
import imgHome8 from  "./allImages/home/imgHome8.webp"
import imgHome9 from  "./allImages/home/imgHome9.webp"
// import imgHome10 from  "./allImages/home/imgHome10.webp"
import imgHome233 from  "./allImages/home/imgHome23.webp"
import imgHome14 from  "./allImages/home/imgHome14.webp"
import imgHome13 from  "./allImages/home/imgHome13.webp"
import imgHome from  "./allImages/home/imgHome.webp"
import imgHome5 from  "./allImages/home/5.webp"
import imgHome6 from  "./allImages/home/seekhStudy.webp"
import modernImg from  "./allImages/home/modern.webp"
import deliveryApp from  "./allImages/home/deliveryapp.webp"
import mooverImg from  "./allImages/home/moover.webp"
import iphone14 from  "./allImages/home/iPhone14-13.webp"
import leranPanda from  "./allImages/home/leranpanda.webp"
import edureka from  "./allImages/home/edureka.webp"
import washiAbout from  "./allImages/about/washiabout (convert.io).webp"
import easyGovLogo from  "./allImages/about/easyGovLogo.webp"
import mooverLogo from  "./allImages/about/mooverLogo.webp"
import dr_audin from  "./allImages/about/dr_audin.webp"
import baymetal from  "./allImages/about/baymetal.webp"
import bmglogo from  "./allImages/about/bmglogo.webp"
import footshoes from  "./allImages/about/footshoes.webp"
import signologo from  "./allImages/about/signologo.webp"
import vivaLifeStyle from  "./allImages/about/VIVA-LIFESTYLES-Logo.webp"
import spiffLogo from  "./allImages/about/spifflogo.webp"
import pplgos from  "./allImages/about/pplgos.webp"
import Raavishsir from  "./allImages/about/Raavish-sir.webp"
import MukeshSir from  "./allImages/about/mukeshsir2.webp"
import aa from  "./allImages/about/aa.webp"
import vineetVerma from  "./allImages/about/vineetVerma.webp"
import vishalGupta from  "./allImages/about/vishalGupta.webp"
import muditMathur from  "./allImages/about/muditMathur.webp"
import imgHome111 from  "./allImages/about/imgHome11.webp"
import mainaboutimg from  "./allImages/about/mainaboutimg.webp"
import groupwq from  "./allImages/about/groupwq.webp"
import imgSdLifeCycle from  "./allImages/about/img-sd-lifecycle.webp"
import dddd from  "./allImages/about/dddd.webp"
import IMAGE21 from  "./allImages/about/IMAGESM21.webp"
import GROUP959 from  "./allImages/about/Grou959.webp"
import imgHome4 from  "./allImages/about/imgHome4.webp"
import demo from  "./allImages/about/demo.webp"
import image286 from "./allImages/autoMotive/image286.webp"
import mobileaccounting from "./allImages/autoMotive/mobileaccounting.webp"
import invoiceaccounting from "./allImages/autoMotive/invoicing26accounts.webp"
import image287 from "./allImages/autoMotive/image287.webp"
import image288 from "./allImages/autoMotive/image288.webp"
import image289 from "./allImages/autoMotive/image289.webp"
import image290 from "./allImages/autoMotive/image290.webp"
import image294 from "./allImages/autoMotive/image294.webp"
import image293 from "./allImages/autoMotive/image293.webp"
import image298 from "./allImages/autoMotive/image298.webp"
import autoMotiveBanner from "./allImages/autoMotive/automotivebanner.webp"
import image282 from "./allImages/autoMotive/image282.webp"
import image2820 from "./allImages/autoMotive/image2820.webp"
import Rt_7 from "./allImages/banking/RT-7banner.webp"
import mobileRt_7 from "./allImages/banking/mobilert-7.webp"
import image266 from "./allImages/banking/image266.webp"
import image263 from "./allImages/banking/image263.webp"
import image269 from "./allImages/banking/image269.webp"
import image271 from "./allImages/banking/image271.webp"
import image272 from "./allImages/banking/image272.webp"
import image273 from "./allImages/banking/image273.webp"
import image276 from "./allImages/banking/image276.webp"
import image280 from "./allImages/banking/image280.webp"
import p41 from "./allImages/banking/P-41.webp"
import p42 from "./allImages/banking/P-42.webp"
import DemoHomeImage from "./allImages/portfolio/oyogroup.webp"
import maskgroup from "./allImages/carrier/Maskgroup.webp"
import financebanner from "./allImages/finance/finacebanner.webp"
import image1521 from "./allImages/finance/image1521.webp"
import image158 from "./allImages/finance/image158.webp"
import image162 from "./allImages/finance/image162.webp"
import image169 from "./allImages/finance/image169.webp"
import image177 from "./allImages/finance/image177.webp"
import food14 from "./allImages/food/food14.webp"
import mobilefoodimg from "./allImages/food/mobilefoodimg.webp"
import food2 from "./allImages/food/food2.webp"
import food5 from "./allImages/food/food5.webp"
import food9 from "./allImages/food/food9.webp"
import food6 from "./allImages/food/food6.webp"
import food8 from "./allImages/food/food8.webp"
import food10 from "./allImages/food/food10.webp"
import food13 from "./allImages/food/food13.webp"
import oyoedu from "./allImages/portfolio/oyoedu.webp"
import img46 from "./allImages/portfolio/46.webp"
import img291 from "./allImages/portfolio/291.webp"
import seekh from "./allImages/portfolio/Seekh.webp"
import img1183 from "./allImages/portfolio/1183.webp"
import autoss from "./allImages/portfolio/autoss.webp"
import autosssImg from "./allImages/portfolio/autossss.webp"
import image229 from "./allImages/realstate/image229.webp"
import image228 from "./allImages/realstate/image228.webp"
import image210 from "./allImages/realstate/image210.webp"
import image211 from "./allImages/realstate/image211.webp"
import image212 from "./allImages/realstate/image212.webp"
import image213 from "./allImages/realstate/image213.webp"
import image214 from "./allImages/realstate/image214.webp"
import image215 from "./allImages/realstate/image215.webp"
import image216 from "./allImages/realstate/image216.webp"
import image217 from "./allImages/realstate/image217.webp"
import image219 from "./allImages/realstate/image219.webp"
import image218 from "./allImages/realstate/image218.webp"
import image220 from "./allImages/realstate/image220.webp"
import image221 from "./allImages/realstate/image221.webp"
import image222 from "./allImages/realstate/image222.webp"
import image223 from "./allImages/realstate/image223.webp"
import image224 from "./allImages/realstate/image224.webp"
import image225 from "./allImages/realstate/image225.webp"
import image226 from "./allImages/realstate/image226.webp"
import image227 from "./allImages/realstate/image227.webp"
import MaskGroup4 from "./allImages/ecommerce/Maskgroup4.webp"
import retailnewimg from "./allImages/ecommerce/retailnewimg.webp"
import howEcommerceWorksImg from "./allImages/ecommerce/how-ecommerce-works1.webp"
import Group963 from "./allImages/ecommerce/Group963.webp"
import image313 from "./allImages/ecommerce/image313.webp"
import image134 from "./allImages/services/image134.webp"
import image135 from "./allImages/services/image135.webp"
import image136 from "./allImages/services/image136.webp"
import image5911 from "./allImages/services/imge5911.webp"
import image138 from "./allImages/services/image138.webp"
import Group886 from "./allImages/services/Group886.webp"
import Execution from "./allImages/services/Execution.webp"
import Group881 from "./allImages/services/Group881.webp"
import Group887 from "./allImages/services/Group887.webp"
import CAD from "./allImages/services/CAD.webp"
import Group883 from "./allImages/services/Group883.webp"
import Group880 from "./allImages/services/Group880.webp"
import Group878 from "./allImages/services/Group878.webp"
import Group877 from "./allImages/services/Group877.webp"
import Group1060 from "./allImages/services/Group1060.webp"
import webservices from "./allImages/services/webservices.webp"














export 
{ wedding0ne, WeddingTwo, logwedding, facebook, twitter, linkedin,erroeImg,homeimg1,homeimg2,homeimg3 ,homeimg52,homeimg21,homeimg22,imgHome3,imghome23,imgHome8,imgHome9,imgHome233,imgHome14,imgHome13,imgHome,imgHome5,imgHome6,modernImg,deliveryApp,mooverImg,iphone14,leranPanda,edureka,washiAbout,easyGovLogo,mooverLogo,dr_audin,baymetal,bmglogo,footshoes,signologo,vivaLifeStyle,spiffLogo,pplgos,Raavishsir,MukeshSir,aa,vineetVerma,vishalGupta,muditMathur,imgHome111,mainaboutimg,groupwq,imgSdLifeCycle,dddd,IMAGE21,GROUP959,imgHome4,demo,image286,mobileaccounting,invoiceaccounting,image287,image288,image289,image290,image294,image293,image298,autoMotiveBanner,image282,image2820,Rt_7,mobileRt_7,image266,image263,image269,image271,image272,image273,image276,image280,p41,p42,DemoHomeImage,maskgroup,financebanner,image1521,image158,image162,image169,image177,food14,mobilefoodimg,food2,food5,food9,food6,food8,food10,food13,oyoedu,img46,img291,seekh,img1183,autoss,autosssImg,image229,image228,image210,image211,image212,image213,image214,image215,image216,image217,image218,image219,image220,image221,image222,image223,image224,image225,image226,image227,MaskGroup4,retailnewimg,howEcommerceWorksImg,Group963,image313,image134,image135,image136,image5911,image138,Group886,Execution,Group881,Group887,CAD,Group883,Group880,Group878,Group1060,Group877,webservices};